backend:
  name: github
  repo: iamweswilson/iamweswilson-timeline
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "site/.vuepress/public/images"
public_folder: "/images"
collections:
  - name: "blog-posts" # Used in routes, e.g., /admin/collections/blog
    label: "Blog Posts" # Used in the UI
    folder: "site/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Author", name: "author", widget: "text" }
      - { label: "Date", name: "date", widget: "date" }
      - { label: "Cateogry", name: "category", widget: "text" }
    editor:
      preview: false

  - name: "main-pages"
    label: "Main Pages"
    editor:
      preview: false

    files:
      - label: "Home Page"
        name: "home-page"
        file: "site/index.md"
        fields:
          - label: Hero
            name: hero
            widget: object
            fields:
              - { label: "Headline", name: headline, widget: string }
              - { label: "Intro", name: intro, widget: text }
          - label: Timeline Entries
            name: values
            widget: list
            allow_add: true
            fields:
              - label: "Year"
                name: year
                widget: number
                default: 2019
                valueType: int
              - label: "Title"
                name: title
                widget: string
              - label: "Copy"
                name: copy
                widget: text
              - label: "Link Text"
                name: linktext
                widget: string
              - label: "URL"
                name: link
                widget: string
              - label: "Additional Link Text"
                name: linktext2
                widget: string
              - label: "Additional URL"
                name: link2
                widget: string

  - name: "settings"
    label: "Settings"
    files:
      - label: "Top Navigation"
        name: "topnav"
        file: "site/pages.json"
        fields:
          - label: Pages
            name: nav
            widget: list
            fields:
              - { label: Name, name: text, widget: string }
              - { label: Link, name: link, widget: string }
